kind: "postgresql"
apiVersion: "acid.zalan.do/v1"
metadata:
  name: images
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "15"
  numberOfInstances: 1

  # enableMasterLoadBalancer: true
  volume:
    size: 2Gi

  resources:
    requests:
      cpu: 100m
      memory: 250Mi
    limits:
      cpu: 2500m
      memory: 3000Mi

  users:
    django: []

  databases:
    images: django