{{- if .Values.runMigrations }}

apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-migrate"
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-it
          image: busybox:1.36
          command: ["sh", "-c", "echo 'Sleeping for 20s...'; sleep 20"]

      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}-utility:{{ .Values.image.tag }}"
          args: ["migrate", "--noinput"]
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.secret }}
                  key: password
            - name: DATABASE_URL
              value: postgres://{{ .Values.postgresql.user }}:$(DB_PASSWORD)@{{ .Values.postgresql.database }}/{{ .Values.postgresql.database }}?sslmode=require

{{- end }}
