# https://opensource.zalando.com/postgres-operator/
kind: "postgresql"
apiVersion: "acid.zalan.do/v1"
metadata:
  name: {{ .Values.postgresql.database }}
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "17"
  numberOfInstances: {{ .Values.postgresql.replicas }}

  # enableMasterLoadBalancer: true
  volume:
    size: {{ .Values.postgresql.size }}

  resources:
    requests: {}
      # cpu: 1000m
      # memory: 250Mi
    limits: {}
      # memory: 3000Mi

  users:
    {{ .Values.postgresql.user }}: []

  databases:
    {{ .Values.postgresql.database }}: {{ .Values.postgresql.user }}

